name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@b27bfcb4c47c8c7deb5a7e90e00aa5e54f44c2f2
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
